export const types = {
  ENTITY_LOAD: "ENTITY_LOAD",
  ENTITY_LOAD_INIT: "ENTITY_LOAD_INIT",
  ENTITY_LOAD_SUCCESS: "ENTITY_LOAD_SUCCESS",
  ENTITY_LOAD_FAILURE: "ENTITY_LOAD_FAILURE",

  ENTITY_SHOW: "ENTITY_SHOW",
  ENTITY_SHOW_INIT: "ENTITY_SHOW_INIT",
  ENTITY_SHOW_SUCCESS: "ENTITY_SHOW_SUCCESS",
  ENTITY_SHOW_FAILURE: "ENTITY_SHOW_FAILURE",

  ENTITY_CREATE_TEXT: "ENTITY_CREATE_TEXT",
  ENTITY_CREATE_TEXT_INIT: "ENTITY_CREATE_TEXT_INIT",
  ENTITY_CREATE_TEXT_SUCCESS: "ENTITY_CREATE_TEXT_SUCCESS",
  ENTITY_CREATE_TEXT_FAILURE: "ENTITY_CREATE_TEXT_FAILURE",
};
