export const types = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGIN_INIT: "AUTH_LOGIN_INIT",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",

  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_LOGOUT_INIT: "AUTH_LOGOUT_INIT",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_FAILURE: "AUTH_LOGOUT_FAILURE",
};
